#######################################################
# Starship Preferences
#######################################################

# Prompt
#######################################################

# Left prompt format
format = """[â•­â”€a/câ”€âœâ‡‰â¯>](bold blue) $username$sudo$time
[â”£â”€sysâ”€â”€â”€âœâ‡‰â¯>](bold yellow) $shell$status$cmd_duration$docker_context$hostname
[â”£â”€projâ”€â”€âœâ‡‰â¯>](bold red) $directory$git_branch$git_commit$git_status
[â•°â”€cmdâ”€âœâ‡‰â¯](bold green) $character"""

# Right prompt format
right_format = """$lua$rust$java$kotlin$dart$python$golang$swift$nodejs$php$conda${custom.docker}$package"""

# Adds a new line after the prompt
add_newline = true
# Max time for the prompt commands to run in milliseconds
command_timeout = 800
# Max time for scaning files in the current directory in milliseconds
scan_timeout = 50


# System
#######################################################

[character]
disabled = false
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold blue)"
format = "$symbol "

[cmd_duration]
disabled = false
show_milliseconds = true
format = "took [$duration](bold yellow) "

[package]
disabled = false
format = "[ğŸ $version](208 bold) "

[shell]
disabled = false
fish_indicator = "ğŸ "
powershell_indicator = "ï‘ _"
unknown_indicator = "â“"
bash_indicator = "ğŸ‘"
zsh_indicator = "ğŸ¦“"
format = "ğŸš:$indicator "

[directory]
disabled = false
truncation_length = 10
truncation_symbol = "â€¦/"
truncate_to_repo = false
home_symbol = "ğŸ¡"
style = "white"

[username]
disabled = false
style_user = "italic bright-purple"
style_root = "red bold"
format = "ğŸ‘¤:[$user]($style) "
show_always = true

[sudo]
disabled = false
style = "bold green"
symbol = "ğŸ§™"
format = "as $symbol "

[time]
disabled = false
format = 'at â°:[\[$time\]](bold yellow) '

[hostname]
disabled = false
ssh_only = false
format = 'on [$hostname](bold red) '
trim_at = "."

[status]
disabled = true
style = "red"
symbol = "ğŸ’¥ "
format = '[\[$symbol$status\]]($style) '

[battery]
disabled = true
full_symbol = "ğŸ’ª"
unknown_symbol = "ğŸ’¡"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’¦"
format = "ğŸ”‹:$symbol "
[[battery.display]]
threshold = 100


# Services
#######################################################

[git_commit]
disabled = true
only_detached = false
tag_disabled = false
style = "red"

[git_branch]
disabled = false
always_show_remote = true
format = "on ğŸŒ±:[$branch](bold yellow) ğŸ‹:[$remote_name/$remote_branch](bold blue) "

[git_status]
disabled = false
ahead = 'ğŸƒ\([$count](bold blue)\)'
diverged = 'ğŸ˜µ\(\(ğŸƒ[$ahead_count](bold blue)\);ğŸŒ\([$behind_count](bold blue)\)\)'
behind = 'ğŸŒ\([$count](bold blue)\)'
conflicted = "ğŸ¤”"
untracked = "ğŸ‘€"
modified = "ğŸ“"
stashed = "ğŸ“¦"
staged = 'ğŸ¤\([$count](bold blue)\)'
renamed = "ğŸ£"
deleted = "ğŸš®"

[docker_context]
disabled = true

# To supress anaconda's own prompt moddifer, run,  conda config --set changeps1 False
[conda]
disabled = false
format = "in [$symbol$environment](dimmed green) "
ignore_base = true


# Programming Languages and Frameworks
#############################################################################
[lua]
disabled = false

[java]
disabled = false

[kotlin]
disabled = false

[dart]
disabled = false

[golang]
disabled = false

[nodejs]
disabled = false

[python]
disabled = false

[rust]
disabled = false

[swift]
disabled = false

[php]
disabled = false

[custom.docker]
disabled = false
description = "Shows a  docker symbol if the current directory has Dockerfile or docker-compose.yml files"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
symbol = "ğŸ³"
format = "with $symbol "

